#Configuracion
#Mon May 11 23:22:46 MST 2026
registration.window.height=490
registration.window.width=500
registration.window.x=692
registration.window.y=287
users.export.pdf=C\:\\Users\\vazxc\\Documents
